name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Use our local setup action
      - uses: ./.github/actions/setup-node-yarn-deps

      - name: Run lint
        run: yarn run lint

  check:
    name: Run check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Use our local setup action
      - uses: ./.github/actions/setup-node-yarn-deps

      - name: Run svelte-check
        run: yarn run check

  build:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Use our local setup action
      - uses: ./.github/actions/setup-node-yarn-deps
      - uses: ./.github/actions/setup-rust-wasm

      - name: Run build
        run: yarn run build
